version: "3.8"

services:
  postgres:
    env_file: .env
    image: postgres:13.7-alpine
  db:
    image: postgres:13.7-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER="$POSTGRES_USER"
      - POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
      - POSTGRES_DB=postgres
    volumes:
      - C:/Software/PostgreSQL/data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
